import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
// import { Spinner } from "@material-tailwind/react";

import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, useSignMessage, useNetwork, useContract, useSigner, useContractRead } from 'wagmi'
import abi from "../abi/contract.json"
import { useEffect, useState } from 'react';
import { ethers } from 'ethers';
import { Alert } from '@material-tailwind/react';
import Loading from '../components/Loading';

interface DonationType {
      name: string;
      donarAddress: string;
      amount: string;
   
}


const Home: NextPage = () => {
  const {isConnected, address} = useAccount()
  const { data: signer, isError, isLoading } = useSigner()
  const contract = useContract({
    address: '0x71855Af0052228dF68962a019E54131b865529De',
    abi: abi,
    signerOrProvider: signer
  })
  const [loading ,setLoading] = useState(true);
  const [allDonations, setAllDonations] = useState<DonationType[]>([])
  const [total, setTotal] = useState(0)
  const { data, isError:a, isLoading:b } = useContractRead({
    address: '0x71855Af0052228dF68962a019E54131b865529De',
    abi: abi,
    functionName: 'getDonars',
  })
  console.log(data)
  console.log(a)
  useEffect(() => {
     const donars = async () => {
      try {
        
        const donations = await contract?.getDonars();
        let result = []
        let totalEth = 0;
        for(let i = 0; i < donations.length; i++) {
          console.log(ethers.utils.formatEther(donations[i].amount))
          totalEth += Number(ethers.utils.formatEther(donations[i].amount))
          result.push({name: donations[i].name, donarAddress: donations[i].donarAddress, 
            amount: ethers.utils.formatEther(donations[i].amount)
          })
        }
        setTotal(totalEth)
        setAllDonations(result)
        setLoading(false)
      } catch (error) {
        console.log(error)
       setLoading(false)
      }
     }
     donars();
  }, [contract])
  // console.log(first)
  return (
    <div className={styles.container}>
      <Head>
        <title>Donations</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
      <div className='max-w-screen-xl mx-auto'>
        {!isConnected ? <Alert className='mt-5'>Please connect your wallet to see the transactions</Alert> :  loading ? 'Loading...' : allDonations?.length > 0 ? 
        <>
        <div className='mt-5 bg-white p-5 flex items-center justify-between'>
          <span className='capitalize text-sm'>total</span>
          <span>{total} eth</span>
        </div>
        <div className='overflow-x-auto'>
        <table className='bg-white w-full my-5 rounded-lg shadow-sm'>
          <thead>
            <tr>
              <th className='text-left uppercase px-3 py-2 font-medium text-sm text-black'>So</th>
              <th className='text-left uppercase px-3 py-2 font-medium text-sm text-black'>name</th>
              <th className='text-left uppercase px-3 py-2 font-medium text-sm text-black'>address</th>
              <th className='text-left uppercase px-3 py-2 font-medium text-sm text-black'>donation</th>
            </tr>
          </thead>
          <tbody>
            {allDonations?.map((donar, index) => (
              <tr className='border-b hover:bg-gray-50 transition-all duration-500' key={index}>
                <td className='text-sm p-5 font-medium text-gray-800'>{index + 1}</td>
                <td className='text-sm p-5 text-gray-800 capitalize font-semibold'>{donar.name}</td>
                <td className='text-sm p-5 font-medium text-gray-800'>{donar.donarAddress}</td>
                <td className='text-sm p-5 font-semibold text-gray-800'>{donar.amount} <span className='uppercase'>eth</span></td>
              </tr>
            ))}
          </tbody>
        </table>
        </div>
        </> : <Loading mt='mt-5' />}
      </div>
      </main>
    </div>
  );
};

export default Home;
